# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller build definition for UPS Label Cropper (Windows).

Build with:

    uv run pyinstaller --clean --noconfirm UPS-Label-Cropper.spec

Design notes (why this looks the way it does):

* **onedir (COLLECT), not onefile.** One-file EXEs self-extract to
  ``%TEMP%\\_MEIxxxxxx`` and run from there, which is the single strongest
  heuristic trigger for Defender's ``Trojan:Win32/Wacatac.B!ml`` ML detections.
  One-dir also lets SumatraPDF ship as a plain file next to the app instead of
  being unpacked-and-executed from temp at runtime.
* **version=... EXE metadata.** Generated by ``build/version_info.py`` so the
  EXE carries CompanyName/ProductName/FileVersion instead of blanks.
* **upx=False everywhere.** Compressing the PE is another strong AV signal,
  and we don't want a stray UPX on the build machine's PATH changing output.
* **datas as tuples.** Platform-agnostic; avoids the Windows ``;`` vs ``:``
  separator footgun of the old ``--add-data`` CLI flags.
"""

import sys
from pathlib import Path

_project_root = Path(SPECPATH).resolve()
sys.path.insert(0, str(_project_root / "build"))
import version_info as _version_info  # noqa: E402

_version_str = _version_info.resolve_version()
_version_file = _version_info.write(_project_root / "build" / "version_info.txt", _version_str)
print(f"[spec] Embedding version {_version_str} into EXE metadata")

a = Analysis(
    [str(_project_root / "src" / "ups_label_cropper" / "__main__.py")],
    pathex=[str(_project_root / "src")],
    binaries=[],
    datas=[
        # assets/ -> _internal/assets (tray icon etc.)
        (str(_project_root / "assets"), "assets"),
        # Bundled SumatraPDF -> _internal/ups_label_cropper/bin/SumatraPDF.exe
        (str(_project_root / "src" / "ups_label_cropper" / "bin"), "ups_label_cropper/bin"),
    ],
    hiddenimports=[
        # Dynamically imported / Windows-only modules PyInstaller may miss.
        "win32print",
        "win32api",
        "win32con",
        "win32gui",
        "infi.systray",
        "watchdog.observers",
        "watchdog.events",
        "fitz",
        "PIL",
        "platformdirs",
        "tkinter",
        "tkinter.ttk",
        "tkinter.messagebox",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Trim obviously-unused heavy deps to keep the bundle small & boring.
        "matplotlib",
        "numpy.tests",
        "pydoc_data",
        "test",
        "unittest",
        "xmlrpc",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

# One-dir layout: EXE holds only the bootloader + PYZ; COLLECT assembles the
# distribution folder (exe + _internal/). Never EXE(a.binaries, a.datas) here,
# that would silently switch us back to the flagged one-file layout.
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="UPS-Label-Cropper",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # GUI/tray app; console window was removed in 1.2.x on purpose
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(_project_root / "assets" / "icon.ico"),
    version=str(_version_file),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="UPS-Label-Cropper",
)
